sign:
  enabled: true
  lifetime:    3600

signHp:
  enabled: true

widgetOuter:
  enabled: true
  lifetime: 60

text:
  enabled: true
  lifetime: 600

_open_actions:
  enabled: true
  contextual: false
  lifetime: 300

page:
  enabled: true
  lifetime: 60
